name: Semgrep Analysis

on: push
jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      pages: write
      id-token: write
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      
      - name: Semgrep scan SARIF
        run: semgrep scan --config="p/default" --sarif --output=report.sarif --metrics=off
      
      - name: Semgrep scan JSON
        run: semgrep scan --config="p/default" --json --output=semgrep.json --metrics=off
      
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install prospector2html
        run: |
          python -m pip install --upgrade pip
          python -m pip install prospector2html
      
      - name: Generate HTML report
        run: prospector-html --input semgrep.json --output semgrep-report.html --filter semgrep
      
      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.html
      
      - name: Prepare GitHub Pages
        run: |
          mkdir -p gh-pages
          cp semgrep-report.html gh-pages/index.html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          publish_branch: gh-pages
